version: '3.8'

services:
  ms-zeeven:
    container_name: ms-zeeven
    image: ms-zeeven:latest
    restart: always
    ports:
      - "8083:8083"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "logging.level.org.springframework.web.cors.DefaultCorsProcessor=debug"
      - "providers.maxmind.licenceKey=${MAXMIND_KEY}"
      - "providers.maxmind.accountId=${MAXMIND_ID}"
      - "providers.whatsapp.token=${WHATSAPP_TOKEN}"
      - "providers.front.host=${ZEEVEN_HOST}"
      - "providers.notifications.host=${NOTIFICATIONS_HOST}"
      - "providers.stripe.key.public=${STRIPE_PUBLIC_KEY}"
      - "providers.stripe.key.secret=${STRIPE_SECRET_KEY}"
      - "providers.stripe.key.webhooksecret=${STRIPE_WEBHOOKSECRET_KEY}"
      - "providers.iplocation.key=${IPLOCATION_API_KEY}"
      - "providers.backoffice.token=${BACKOFFICE_API_KEY}"
      - "spring.rabbitmq.host=${RABBITMQ_IP}"
      - "spring.rabbitmq.port=${RABBITMQ_PORT}"
      - "spring.rabbitmq.password=${RABBITMQ_PASSWORD}"
      - "spring.rabbitmq.username=${RABBITMQ_USERNAME}"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-zeeven.rule=Headers(`X-Host`, `api.zeeven.chillo.fr`)"
      - "traefik.docker.network=applications-network"
      - "traefik.http.routers.service.middlewares=serviceheaders"
      - "traefik.http.middlewares.serviceheaders.headers.accesscontrolalloworiginlist=*" 

    volumes:
      - "/var/www/:/var/www/"
    networks:
      - applications-network
networks:
  applications-network:
    external: true
    name: applications-network
