server:
  servlet:
    context-path: /api
  port: 8087

spring:
    application:
      name: ms-zeeven
    mail:
      host: localhost
      port: 25

mongock:
  migration-scan-package:
    - com.cs.ge.configuration

jwt:
  header: "Authorization"
  secret: "AL_KEY"
  expiration: 3600 # (secondes) == 1 heure
  route:
    authentication:
      path: "/login"
      refresh: "/refresh"

