app:
  host: http://app.zeeven.chillo.fr
spring:
  data:
    mongodb:
      host: db-mongo
  mail:
      #host:  mails.dev
      accountLink: ${app.host}/activer-mon-compte?code=


resources:
  images:
    host: https://api.zeeven.chillo.fr
    root: /var/www





