app:
  host: http://localhost:3000
spring:
  data:
    mongodb:
      host: localhost
      port: 27017

  mail:
      accountLink: ${app.host}/activer-mon-compte?code=

resources:
  images:
    host: https://api.zeeven.chillo.fr
    root: /Users/chillo/projets/zeeven
    folder: images






