server:
  servlet:
    context-path: /api
  port: 8080
app:
  host: http://app.zeeven.com
spring:
  application:
    name: ms-zeeven
  mail:
    activation-url: ${app.host}/activer-mon-compte?code=
    password-url: ${app.host}/activer-mon-compte?code=
    new-password-url: ${app.host}/activer-mon-compte?code=
    host: smtp.gmail.com
    port: 587
    password: hnucjwtwmqaqymdr
    username: bonjour.zeeven@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: 'smtp'
          auth: true
          starttls:
            enable: true
            required: true

mongock:
  migration-scan-package:
    - com.cs.ge.changelog

jwt:
  header: 'Authorization'
  secret: 'AL_KEY'
  expiration: 3600 # (secondes) == 1 heure
  route:
    authentication:
      path: '/login'
      refresh: '/refresh'
providers:
  whatsapp:
    host: https://graph.facebook.com/v13.0/${providers.whatsapp.phone}
    phone: 108190935266755
    token: EAAIDpGRyY6MBAPSNYZCs3g6MbCk6k1Nl63Pst4qOA37R2OrV0MoSS306ci25sVG6LKl4YbIZAuaWZBamS2VleykUa8zMfkEeb82vMZAdlFryTGIjGSgjWUT2ndU7f5hYtqEEyU7d1ZBoLytEN5gjjoKP6RTVlNjqYvkJmI6kBEq1sLTFSbsHv2wPKhTrYaJYoqETCrQFmTQZDZD
logging:
  level:
    org:
      springframework: INFO
cors:
  urls: 'http://localhost:3000,https://app.zeeven.chillo.fr'
