app:
  host: http://localhost:3000
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin

  mail:
      host: localhost
      port: 25
      accountLink: ${app.host}/activer-mon-compte?code=
providers:
    notifications:
        host: http://localhost:9092
resources:
  images:
    host: https://zeeven.fr
    root: /Users/chillo/projets/zeeven
    folder: images






