server:
  servlet:
    context-path: /api
  port: 8083
app:
  host: http://app.zeeven.com
spring:
  data:
    mongodb:
      database: db-zeeven
  application:
    name: ms-zeeven
  mail:
    activation-url: ${app.host}/activer-mon-compte?code=
    password-url: ${app.host}/activer-mon-compte?code=
    new-password-url: ${app.host}/activer-mon-compte?code=
    host: smtp.gmail.com
    port: 587
    password: xpmswzbclbnulucd
    username: bonjour.zeeven@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: 'smtp'
          auth: true
          starttls:
            enable: true
            required: true

mongock:
  migration-scan-package:
    - com.cs.ge.changelog

jwt:
  header: 'Authorization'
  secret: 'AL_KEY'
  expiration: 3600 # (secondes) == 1 heure
  route:
    authentication:
      path: '/login'
      refresh: '/refresh'
providers:
  whatsapp:
    host: https://graph.facebook.com/v13.0/${providers.whatsapp.phone}
    phone: 108190935266755
  twilio:
    ACCOUNT_SID: ACcbb01f55e3469ff5eea683ebc1aac50f
    AUTH_TOKEN: 1778b79bac3e35612ed996f5cb2531f4

cors:
  urls: 'http://localhost:3000,https://app.zeeven.chillo.fr'
resources:
  images:
    folder: "applications/zeeven/images"
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
logging:
  level:
    com.cs.ge: DEBUG
org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG
