app:
  host: http://app.zeeven.chillo.fr
spring:
  data:
    mongodb:
      host: db-mongo
      database: zeeven
  mail:
      host: http://app.zeeven.chillo.fr
      accountLink: ${app.host}/activer-mon-compte?code=








