app:
  host: http://api.zeeven.chillo.fr
spring:
  rabbitmq:
    host: 212.83.180.65
  data:
    mongodb:
      host: db-zeeven
  mail:
      #host:  mails.dev
      accountLink: ${app.host}/activer-mon-compte?code=


resources:
  images:
    host: https://app.zeeven.chillo.fr
    root: /var/www

org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG





