on:
  push:
    branches:
      - feature/*
      - develop
  workflow_dispatch:
permissions:
  contents: read

jobs:
  define-variables:
    name: JOB Define variables
    runs-on: ubuntu-latest
    outputs:
      APPLICATIONS_HOST: ${{ steps.step-define-variables.outputs.APPLICATIONS_HOST }}
      APPLICATIONS_PORT: ${{ steps.step-define-variables.outputs.APPLICATIONS_PORT }}
      APPLICATIONS_USERNAME: ${{ steps.step-define-variables.outputs.APPLICATIONS_USERNAME }}
      IPLOCATION_API_KEY: ${{ steps.step-define-variables.outputs.IPLOCATION_API_KEY }}
      BACKOFFICE_API_KEY: ${{ steps.step-define-variables.outputs.BACKOFFICE_API_KEY }}
      APPLICATIONS_SSH_PRIVATE_KEY: ${{ steps.step-define-variables.outputs.APPLICATIONS_SSH_PRIVATE_KEY }}
    steps:
      - name: STEP Define variables
        id: step-define-variables
        run: |
          echo "APPLICATIONS_HOST=${{ secrets.RECETTE_APPLICATIONS_HOST }}" >> $GITHUB_OUTPUT
          echo "APPLICATIONS_PORT=${{ secrets.RECETTE_APPLICATIONS_PORT }}" >> $GITHUB_OUTPUT
          echo "APPLICATIONS_USERNAME=${{ secrets.RECETTE_APPLICATIONS_USERNAME }}" >> $GITHUB_OUTPUT
          echo "IPLOCATION_API_KEY=${{ secrets.RECETTE_IPLOCATION_API_KEY }}" >> $GITHUB_OUTPUT
          echo "BACKOFFICE_API_KEY=${{ secrets.RECETTE_BACKOFFICE_API_KEY }}" >> $GITHUB_OUTPUT
          echo "APPLICATIONS_SSH_PRIVATE_KEY=${{ secrets.RECETTE_APPLICATIONS_SSH_PRIVATE_KEY }}" >> $GITHUB_OUTPUT

  create-folder:
    name: Create folder
    runs-on: ubuntu-latest
    needs: define-variables
    steps:
      - name: Display variables
        run: |
          echo "HOST ${{ needs.define-variables.outputs.APPLICATIONS_HOST }}"
