on:
  push:
    branches:
      - feature/*
      - develop
  workflow_dispatch:
permissions:
  contents: read

jobs:
  define-variables:
    name: JOB Define variables
    runs-on: ubuntu-latest
    outputs:
      APPLICATIONS_HOST: ${{ steps.step-define-variables.outputs.APPLICATIONS_HOST }}
    steps:
      - name: STEP Define variables
        id: step-define-variables
        run: |
          echo "APPLICATIONS_HOST=${{ secrets.PROD_APPLICATIONS_HOST }}" >> $GITHUB_OUTPUT

  debug-variables:
    name: JOB Debug variables
    runs-on: ubuntu-latest
    needs: define-variables
    steps:
      - name: Display variables
        run: |
          echo "HOST ${{ needs.define-variables.outputs.APPLICATIONS_HOST }}"
