on:
  push:
    branches:
      - feature/*
      - develop
  workflow_dispatch:
permissions:
  contents: read

env:
  NODE_VERSION: '14.x'
  APPLICATION_NAME: 'zeeven'
  APPLICATION_TYPE: 'ms'

jobs:
  debug-variables:
    name: JOB Debug variables
    runs-on: ubuntu-latest
    steps:
      - name: Create folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APPLICATIONS_HOST }}
          port: ${{ secrets.APPLICATIONS_PORT }}
          username: ${{secrets.APPLICATIONS_USERNAME }}
          key: ${{ secrets.APPLICATIONS_SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /opt/applications/${{env.APPLICATION_NAME}}/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}
            sudo chmod ugo+rwx /opt/applications/${{env.APPLICATION_NAME}}/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}
