on:
  push:
    branches:
      - feature/*
      - develop
  workflow_dispatch:
permissions:
  contents: read

env:
  NODE_VERSION: '14.x'
  APPLICATION_NAME: 'zeeven'
  APPLICATION_TYPE: 'ms'

jobs:
  create-staging-folder:
    name: create folder
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master' && github.ref == 'refs/heads/master' }}
    environment:
      name: production
    steps:
      - uses: actions/checkout@master
      - name: Create folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APPLICATIONS_HOST }}
          port: ${{ secrets.APPLICATIONS_PORT }}
          username: ${{ secrets.APPLICATIONS_USERNAME }}
          key: ${{ secrets.APPLICATIONS_SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /opt/applications/${{env.APPLICATION_NAME}}/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}
            sudo chmod ugo+rwx /opt/applications/${{env.APPLICATION_NAME}}/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}
  create-prod-folde:
    name: create folder
    runs-on: ubuntu-latest
    if: ${{ !(github.base_ref == 'master' && github.ref == 'refs/heads/master') }}
    environment:
      name: staging
    steps:
      - uses: actions/checkout@master
      - name: Create folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APPLICATIONS_HOST }}
          port: ${{ secrets.APPLICATIONS_PORT }}
          username: ${{ secrets.APPLICATIONS_USERNAME }}
          key: ${{ secrets.APPLICATIONS_SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /opt/applications/${{env.APPLICATION_NAME}}/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}
            sudo chmod ugo+rwx /opt/applications/${{env.APPLICATION_NAME}}/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}

      - name: update configs
        run: |
          sed -i 's|IMAGE_NAME|simachille/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}:${{ github.sha }}|' docker-compose.yml

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.APPLICATIONS_HOST }}
          port: ${{ secrets.APPLICATIONS_PORT }}
          username: ${{ secrets.APPLICATIONS_USERNAME }}
          key: ${{ secrets.APPLICATIONS_SSH_PRIVATE_KEY }}
          source: 'docker-compose.yml'
          target: '/opt/applications/${{env.APPLICATION_NAME}}/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}'
