on:
  push:
    branches:
      - feature/*
      - develop
  workflow_dispatch:
permissions:
  contents: read

jobs:
  define-variables:
    name: JOB Define variables
    runs-on: ubuntu-latest
    steps:
      - name: STEP Define variables
        id: step-define-variables
        run: |
          echo "::set-output name=APPLICATIONS_HOST::$secrets.PROD_APPLICATIONS_HOST"

  debug-variables:
    name: JOB Debug variables
    runs-on: ubuntu-latest
    steps:
      - name: Display variables
        run: |
          echo "HOST ${{ needs.define-variables.outputs.APPLICATIONS_HOST }}"
